//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("0.2.0")]
[assembly: AssemblyFileVersion("0.2.0.0")]
[assembly: AssemblyCopyright("Copyright © Onpoint On Demand 2011")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCompany("Onpoint On Demand")]
[assembly: AssemblyProduct("Fluent JDF (Debug DB: 0)")]


