// This file was generated by C# Refactory.
// To modify this template, go to Tools/Options/C# Refactory/Code

using System;
using System.Runtime.Serialization;

namespace FluentJdf.Template
{
	/// <summary>
	/// Generic exception for the template namespace.
	/// </summary>
	[Serializable]
	public class TemplateApiException : Exception
	{	
		/// <summary>
		/// Default constructor.
		/// </summary>
		public TemplateApiException()
		{
		}

		/// <summary>
		/// Construct an instance with a particular error message.
		/// </summary>
		/// <param name="Message">The error message.</param>
		public TemplateApiException(string Message) : base(Message)
		{
		}

		/// <summary>
		/// Construct an instance with a specific error message and an inner exception.
		/// </summary>
		/// <param name="Message">The error message.</param>
		/// <param name="Inner">The inner exception.</param>
		public TemplateApiException(string Message, Exception Inner) : base(Message, Inner)
		{
		}
		
		/// <summary>
		/// For serialization.
		/// </summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected TemplateApiException(SerializationInfo info,
			StreamingContext context) : base(info, context)
		{
		}
	}

}